# Generated by Django 2.2.7 on 2019-12-17 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_role_group'),
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='opened_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='variety',
            field=models.CharField(choices=[('public', 'Terbuka'), ('private', 'Tertutup')], default='public', max_length=100),
        ),
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=355)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_groups', to='person.Person')),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Groups',
                'db_table': 'debate_access_group',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='access_group',
            field=models.ManyToManyField(related_name='topics', to='debate.AccessGroup'),
        ),
        migrations.CreateModel(
            name='AccessEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_emails', to='debate.AccessGroup')),
            ],
            options={
                'verbose_name': 'Access Email',
                'verbose_name_plural': 'Access Emails',
                'db_table': 'debate_access_email',
                'abstract': False,
                'unique_together': {('group', 'email')},
            },
        ),
    ]
