# Generated by Django 2.2.7 on 2019-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20191217_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='access_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='debate.AccessGroup'),
        ),
    ]
