# Generated by Django 2.2.7 on 2019-12-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20191217_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='variety',
            new_name='access',
        ),
        migrations.AlterField(
            model_name='topic',
            name='access_group',
            field=models.ManyToManyField(blank=True, related_name='topics', to='debate.AccessGroup'),
        ),
    ]
