# Generated by Django 2.2.7 on 2019-12-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20191217_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-date_created',), 'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-date_created',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RenameField(
            model_name='accessemail',
            old_name='group',
            new_name='access_group',
        ),
        migrations.AlterUniqueTogether(
            name='accessemail',
            unique_together={('access_group', 'email')},
        ),
    ]
