# Generated by Django 2.2.7 on 2019-12-23 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_auto_20191222_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('member', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('access_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_members', to='debate.AccessGroup')),
            ],
            options={
                'verbose_name': 'Access Member',
                'verbose_name_plural': 'Access Members',
                'db_table': 'debate_access_member',
                'abstract': False,
                'unique_together': {('access_group', 'member')},
            },
        ),
        migrations.DeleteModel(
            name='AccessEmail',
        ),
    ]
