# Generated by Django 2.2.7 on 2019-11-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='content_type',
            field=models.ManyToManyField(limit_choices_to=models.Q(app_label='person'), related_name='person_attibutes', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label='person'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='validation',
            name='content_type',
            field=models.ManyToManyField(limit_choices_to=models.Q(app_label='person'), related_name='person_validations', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='validationvalue',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(app_label='person'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='validationvalue',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
