# Generated by Django 2.2.7 on 2019-11-22 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0002_auto_20191121_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Projek',
                'verbose_name_plural': 'Projek',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(limit_choices_to={'is_cluster': True}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_cluster', to='person.Project')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'db_table': 'projects_cluster',
            },
        ),
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(choices=[(1, 'Ready'), (2, 'Indent')], default=1)),
                ('is_over_credit', models.BooleanField(null=True)),
                ('sertifikat', models.CharField(choices=[('SHM', 'SHM'), ('SHGB', 'SHGB')], max_length=255, null=True)),
                ('blok', models.CharField(max_length=255)),
                ('nomor', models.CharField(max_length=255)),
                ('tipe', models.CharField(max_length=255)),
                ('jumlah_lantai', models.CharField(max_length=255, null=True)),
                ('kamar_tidur', models.CharField(max_length=255, null=True)),
                ('kamar_mandi', models.CharField(max_length=255, null=True)),
                ('garasi', models.CharField(max_length=255, null=True)),
                ('carport', models.CharField(max_length=255, null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
                ('harga', models.CharField(max_length=255)),
                ('uang_muka', models.CharField(max_length=255)),
                ('luas_tanah', models.CharField(max_length=255)),
                ('luas_bangunan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(max_length=5000)),
                ('contact_person_name', models.CharField(max_length=255, null=True)),
                ('contact_person_number', models.CharField(max_length=255, null=True)),
                ('contact_person_keterangan', models.TextField(null=True)),
                ('komisi', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_unit', to='person.ProjectCluster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_unit', to='person.Project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'projects_unit',
            },
        ),
    ]
