# Generated by Django 2.2.7 on 2019-11-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_project_projectcluster_projectunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcluster',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectunit',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='projectunit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectunit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectunit',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCluster',
        ),
        migrations.DeleteModel(
            name='ProjectUnit',
        ),
    ]
