# Generated by Django 2.2.7 on 2019-11-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20191124_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='option_group',
            field=models.ForeignKey(blank=True, help_text='Select option group if using type "Option" or "Multi Option"', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_attributes', to='person.AttributeOptionGroup', verbose_name='Option Group'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='method',
            field=models.CharField(choices=[('auto', 'Auto'), ('sms', 'SMS'), ('manual', 'Manual')], help_text='Verification method', max_length=255, null=True),
        ),
    ]
