# Generated by Django 2.2.7 on 2019-11-28 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('person', '0006_auto_20191127_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='securecode',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label='person'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='securecode',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('manual', 'Manual')], help_text='Verification method', max_length=255, null=True),
        ),
    ]
