# Generated by Django 2.2.7 on 2019-11-28 04:06

import django.core.validators
from django.db import migrations, models
import utils.generals


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20191128_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securecode',
            name='behavior',
        ),
        migrations.AddField(
            model_name='securecode',
            name='identifier',
            field=models.SlugField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(message="Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit.", regex='^[a-zA-Z_][0-9a-zA-Z_]*$'), utils.generals.non_python_keyword], verbose_name='Identifier'),
        ),
    ]
