# Generated by Django 2.2.7 on 2019-12-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20191128_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationvalue',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
