# Generated by Django 2.2.7 on 2019-12-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20191211_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='required',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='secured',
            new_name='is_secured',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='required',
            new_name='is_required',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='secured',
            new_name='is_secured',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='unique',
            new_name='is_unique',
        ),
    ]
