# Generated by Django 2.2.7 on 2019-12-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20191211_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='required',
        ),
    ]
