# Generated by Django 2.2.7 on 2019-12-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('person', '0012_groupextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupExtend',
        ),
    ]
